feign:
  client:
    config:
      feignName: ttt # 需要配置的FeignName
        connectTimeout: 5000 # 连接超时时间
        readTimeout: 5000 # 读超时时间
        loggerLebel: full # 配置Feign的日志级别
        errorDecoder: com.example.SimpleErrorDecoder #Feign的错误解码器
        retryer: com.example.SimpleRetryer #配置重试
        requestInterceptors: #配置拦截器
          - com.example.FooRequesttInterceptor
          - com.example.BarRequesttInterceptor
        decoder404: false
        encoder: com.example.SimpleEncoder #feign编码器
        decoder: com.example.SimpleDecoder #feign解码器
        contract: com.example.SimpleContrace #feign的Contract配置


feign:
  client:
    config:
      default:
        connectTimeout: 5000