logging:
  level:
    xin.liujiajun.feign.hello.service.HelloFeignService: debug
---
spring:
  profiles: dev
feign:
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
