spring:
  application:
    name: ribbon
server:
  port: 7777
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
  instance:
    prefer-ip-address: true

client-a:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#client-a:
#  ribbon:
#    ConnectTimeout: 3000
#    ReadTimeout: 60000
#    MaxAutoRetries: 1 #对第一次请求的服务的重试次数
#    MaxAutoRetriesNextServer: 1 #要重试的下一个服务的最大数量（不包括第一个服务）
#    OkToRetryOnAllOperations: true
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#ribbon:
#  eager-load:
#    enabled: true
#    clients: client-a, client-b, client-c

#ribbon:
#  eureka:
#    enabled: false
#
#client:
#  ribbon:
#    listofServers: http://localhost:7070，http://localhost:7071